/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobRole = IDL.Record({
  'title' : IDL.Text,
  'verificationScore' : IDL.Nat,
  'aiAdoptionPercent' : IDL.Nat,
  'salaryRange' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const AnalysisResult = IDL.Record({
  'alignmentPercent' : IDL.Nat,
  'branch' : IDL.Text,
  'suggestions' : IDL.Vec(IDL.Text),
  'conflictPoints' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ConsultationRequest = IDL.Record({
  'userName' : IDL.Text,
  'userEmail' : IDL.Text,
  'paid' : IDL.Bool,
  'role' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ProjectComponent = IDL.Record({
  'aiRatio' : IDL.Nat,
  'humanIntelligenceRatio' : IDL.Nat,
  'name' : IDL.Text,
  'recommendedTech' : IDL.Text,
});
export const ProjectIdea = IDL.Record({
  'idea' : IDL.Text,
  'components' : IDL.Vec(ProjectComponent),
});

export const idlService = IDL.Service({
  'addJobRole' : IDL.Func([JobRole], [], []),
  'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getConsultations' : IDL.Func([], [IDL.Vec(ConsultationRequest)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(ProjectIdea)], ['query']),
  'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
  'submitAnalysis' : IDL.Func([AnalysisResult], [], []),
  'submitContact' : IDL.Func([ContactSubmission], [], []),
  'submitProject' : IDL.Func([ProjectIdea], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobRole = IDL.Record({
    'title' : IDL.Text,
    'verificationScore' : IDL.Nat,
    'aiAdoptionPercent' : IDL.Nat,
    'salaryRange' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const AnalysisResult = IDL.Record({
    'alignmentPercent' : IDL.Nat,
    'branch' : IDL.Text,
    'suggestions' : IDL.Vec(IDL.Text),
    'conflictPoints' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ConsultationRequest = IDL.Record({
    'userName' : IDL.Text,
    'userEmail' : IDL.Text,
    'paid' : IDL.Bool,
    'role' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ProjectComponent = IDL.Record({
    'aiRatio' : IDL.Nat,
    'humanIntelligenceRatio' : IDL.Nat,
    'name' : IDL.Text,
    'recommendedTech' : IDL.Text,
  });
  const ProjectIdea = IDL.Record({
    'idea' : IDL.Text,
    'components' : IDL.Vec(ProjectComponent),
  });
  
  return IDL.Service({
    'addJobRole' : IDL.Func([JobRole], [], []),
    'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getConsultations' : IDL.Func(
        [],
        [IDL.Vec(ConsultationRequest)],
        ['query'],
      ),
    'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(ProjectIdea)], ['query']),
    'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
    'submitAnalysis' : IDL.Func([AnalysisResult], [], []),
    'submitContact' : IDL.Func([ContactSubmission], [], []),
    'submitProject' : IDL.Func([ProjectIdea], [], []),
  });
};

export const init = ({ IDL }) => { return []; };