/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'alignmentPercent' : bigint,
  'branch' : string,
  'suggestions' : Array<string>,
  'conflictPoints' : Array<[string, string]>,
}
export interface ConsultationRequest {
  'userName' : string,
  'userEmail' : string,
  'paid' : boolean,
  'role' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface JobRole {
  'title' : string,
  'verificationScore' : bigint,
  'aiAdoptionPercent' : bigint,
  'salaryRange' : string,
  'requiredSkills' : Array<string>,
}
export interface ProjectComponent {
  'aiRatio' : bigint,
  'humanIntelligenceRatio' : bigint,
  'name' : string,
  'recommendedTech' : string,
}
export interface ProjectIdea {
  'idea' : string,
  'components' : Array<ProjectComponent>,
}
export interface _SERVICE {
  'addJobRole' : ActorMethod<[JobRole], undefined>,
  'getAllAnalyses' : ActorMethod<[], Array<AnalysisResult>>,
  'getConsultations' : ActorMethod<[], Array<ConsultationRequest>>,
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getJobRoles' : ActorMethod<[], Array<JobRole>>,
  'getProjects' : ActorMethod<[], Array<ProjectIdea>>,
  'requestConsultation' : ActorMethod<[ConsultationRequest], undefined>,
  'submitAnalysis' : ActorMethod<[AnalysisResult], undefined>,
  'submitContact' : ActorMethod<[ContactSubmission], undefined>,
  'submitProject' : ActorMethod<[ProjectIdea], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];